server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates: 
                - Path=/orders/core/**

              filters:
                - name: InventoryFilter
                - name: AuthenticationFilter

            - id: INVENTORY-SERVICE
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/products/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    reactor.netty.http.server: DEBUG

jwt:
  secretKey:
    knujkb5sgdbdh48h44c5b4d8th48rg4s4dxh8xh48d4b
